apiVersion: v1
kind: Service
metadata:
  name: nginx-servicelb
  labels:
    owner: ramesh
spec:
  selector:
    app.kubernetes.io/name: proxy
  type: LoadBalancer
  ports:
  - name: name-of-service-port
    protocol: TCP
    port: 80
    targetPort: 8080